#pragma once
#include <unordered_map>
#include <SFML/Window/Keyboard.hpp>
#include <imgui.h>

std::unordered_map<ImGuiKey, sf::Keyboard::Key> ImGuiToSFMLKeyMap = {
    { ImGuiKey_Tab, sf::Keyboard::Tab },
    { ImGuiKey_LeftArrow, sf::Keyboard::Left },
    { ImGuiKey_RightArrow, sf::Keyboard::Right },
    { ImGuiKey_UpArrow, sf::Keyboard::Up },
    { ImGuiKey_DownArrow, sf::Keyboard::Down },
    { ImGuiKey_PageUp, sf::Keyboard::PageUp },
    { ImGuiKey_PageDown, sf::Keyboard::PageDown },
    { ImGuiKey_Home, sf::Keyboard::Home },
    { ImGuiKey_End, sf::Keyboard::End },
    { ImGuiKey_Insert, sf::Keyboard::Insert },
    { ImGuiKey_Delete, sf::Keyboard::Delete },
    { ImGuiKey_Backspace, sf::Keyboard::Backspace },
    { ImGuiKey_Space, sf::Keyboard::Space },
    { ImGuiKey_Enter, sf::Keyboard::Enter },
    { ImGuiKey_Escape, sf::Keyboard::Escape },
    { ImGuiKey_LeftCtrl, sf::Keyboard::LControl },
    { ImGuiKey_LeftShift, sf::Keyboard::LShift },
    { ImGuiKey_LeftAlt, sf::Keyboard::LAlt },
    { ImGuiKey_LeftSuper, sf::Keyboard::LSystem },
    { ImGuiKey_RightCtrl, sf::Keyboard::RControl },
    { ImGuiKey_RightShift, sf::Keyboard::RShift },
    { ImGuiKey_RightAlt, sf::Keyboard::RAlt },
    { ImGuiKey_RightSuper, sf::Keyboard::RSystem },
    { ImGuiKey_Menu, sf::Keyboard::Menu },

    // Numbers
    { ImGuiKey_0, sf::Keyboard::Num0 },
    { ImGuiKey_1, sf::Keyboard::Num1 },
    { ImGuiKey_2, sf::Keyboard::Num2 },
    { ImGuiKey_3, sf::Keyboard::Num3 },
    { ImGuiKey_4, sf::Keyboard::Num4 },
    { ImGuiKey_5, sf::Keyboard::Num5 },
    { ImGuiKey_6, sf::Keyboard::Num6 },
    { ImGuiKey_7, sf::Keyboard::Num7 },
    { ImGuiKey_8, sf::Keyboard::Num8 },
    { ImGuiKey_9, sf::Keyboard::Num9 },

    // Letters
    { ImGuiKey_A, sf::Keyboard::A },
    { ImGuiKey_B, sf::Keyboard::B },
    { ImGuiKey_C, sf::Keyboard::C },
    { ImGuiKey_D, sf::Keyboard::D },
    { ImGuiKey_E, sf::Keyboard::E },
    { ImGuiKey_F, sf::Keyboard::F },
    { ImGuiKey_G, sf::Keyboard::G },
    { ImGuiKey_H, sf::Keyboard::H },
    { ImGuiKey_I, sf::Keyboard::I },
    { ImGuiKey_J, sf::Keyboard::J },
    { ImGuiKey_K, sf::Keyboard::K },
    { ImGuiKey_L, sf::Keyboard::L },
    { ImGuiKey_M, sf::Keyboard::M },
    { ImGuiKey_N, sf::Keyboard::N },
    { ImGuiKey_O, sf::Keyboard::O },
    { ImGuiKey_P, sf::Keyboard::P },
    { ImGuiKey_Q, sf::Keyboard::Q },
    { ImGuiKey_R, sf::Keyboard::R },
    { ImGuiKey_S, sf::Keyboard::S },
    { ImGuiKey_T, sf::Keyboard::T },
    { ImGuiKey_U, sf::Keyboard::U },
    { ImGuiKey_V, sf::Keyboard::V },
    { ImGuiKey_W, sf::Keyboard::W },
    { ImGuiKey_X, sf::Keyboard::X },
    { ImGuiKey_Y, sf::Keyboard::Y },
    { ImGuiKey_Z, sf::Keyboard::Z },

    // Function keys
    { ImGuiKey_F1, sf::Keyboard::F1 },
    { ImGuiKey_F2, sf::Keyboard::F2 },
    { ImGuiKey_F3, sf::Keyboard::F3 },
    { ImGuiKey_F4, sf::Keyboard::F4 },
    { ImGuiKey_F5, sf::Keyboard::F5 },
    { ImGuiKey_F6, sf::Keyboard::F6 },
    { ImGuiKey_F7, sf::Keyboard::F7 },
    { ImGuiKey_F8, sf::Keyboard::F8 },
    { ImGuiKey_F9, sf::Keyboard::F9 },
    { ImGuiKey_F10, sf::Keyboard::F10 },
    { ImGuiKey_F11, sf::Keyboard::F11 },
    { ImGuiKey_F12, sf::Keyboard::F12 },

    // Keypad
    { ImGuiKey_Keypad0, sf::Keyboard::Numpad0 },
    { ImGuiKey_Keypad1, sf::Keyboard::Numpad1 },
    { ImGuiKey_Keypad2, sf::Keyboard::Numpad2 },
    { ImGuiKey_Keypad3, sf::Keyboard::Numpad3 },
    { ImGuiKey_Keypad4, sf::Keyboard::Numpad4 },
    { ImGuiKey_Keypad5, sf::Keyboard::Numpad5 },
    { ImGuiKey_Keypad6, sf::Keyboard::Numpad6 },
    { ImGuiKey_Keypad7, sf::Keyboard::Numpad7 },
    { ImGuiKey_Keypad8, sf::Keyboard::Numpad8 },
    { ImGuiKey_Keypad9, sf::Keyboard::Numpad9 },
    { ImGuiKey_KeypadDecimal, sf::Keyboard::Period },
    { ImGuiKey_KeypadDivide, sf::Keyboard::Divide },
    { ImGuiKey_KeypadMultiply, sf::Keyboard::Multiply },
    { ImGuiKey_KeypadSubtract, sf::Keyboard::Subtract },
    { ImGuiKey_KeypadAdd, sf::Keyboard::Add },
    { ImGuiKey_KeypadEnter, sf::Keyboard::Enter },
    { ImGuiKey_KeypadEqual, sf::Keyboard::Equal },

    // Misc punctuation keys (if needed)
    { ImGuiKey_Equal, sf::Keyboard::Equal },
    { ImGuiKey_Minus, sf::Keyboard::Hyphen },
    { ImGuiKey_Comma, sf::Keyboard::Comma },
    { ImGuiKey_Period, sf::Keyboard::Period },
    { ImGuiKey_Slash, sf::Keyboard::Slash },
    { ImGuiKey_Semicolon, sf::Keyboard::SemiColon },
    { ImGuiKey_Apostrophe, sf::Keyboard::Quote },
    { ImGuiKey_LeftBracket, sf::Keyboard::LBracket },
    { ImGuiKey_Backslash, sf::Keyboard::Backslash },
    { ImGuiKey_RightBracket, sf::Keyboard::RBracket },
    { ImGuiKey_GraveAccent, sf::Keyboard::Tilde },
};